name: Hello World
on:
    pull_request:
        types: [opened]
jobs:
    startup:
        name: Run startup script
        runs-on: ubuntu-latest
        steps:
            - run: echo "hello world"
    build:
        name: Runing Build Task
        runs-on: ubuntu-latest
        needs: startup
        steps:
            - run: gh pr comment $PR_URL --body "Thanks for the PR"
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                PR_URL: ${{ github.event.pull_request.html_url }}

    